name: invest_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations: # Add this line
    sdk: flutter 

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.0
  expandable: ^5.0.1
  intl: ^0.17.0
  flutter_svg: ^2.0.5
  image_picker: ^1.0.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
